### ISSUE TITLE
header / navbar

### ISSUE THREAD

**Issue by dadtmt** [El-Loco-Pinguino/wcs-static-project#18]
navbar should be in the header
header can have the container class

**Comment by AurelieBayre** [comment]
[Commit resolving this issue](https://github.com/El-Loco-Pinguino/wcs-static-project/commit/30ca23d22e75cf0eaf7ae184f8c8273a3d4b3b43).

**Comment by El-Loco-Pinguino** [comment]
If that issue is definitely solved, you can close it by clicking the "Close issue" button below the messages.

**Comment by AurelieBayre** [comment]
@El-Loco-Pinguino Was the preceding comment addressed to me? because I don't have the ability to close an issue here, but as the owner, you probably have that right. Besides, you're the coordinator! :P
